### PR TITLE
Updated nuget packages.

### PR DESCRIPTION
**Pull request by yurkinh**
Updated all nuget packages for all platforms.
Updated OkHttp RequestBody.Create() in OkHttpNetworkHandler method due to deprecation in OkHttp 4.2.2 version

### CODE REVIEW

**Comment by jded76** [comment]
Hi yurkinh. 
OkHttp version 4.x is not compatible with older androids. 
See my comment [here](https://github.com/alexrainman/ModernHttpClient/issues/57#issuecomment-552224532)

I think its too early to stop supporting android 5.

**Comment by alexrainman** [comment]
Fully agree.

**Comment by yurkinh** [comment]
I have downgraded OkHttp version to 3.12.6 hence it should be compatible with old android versions. And it is a bit newer then version 3.8.1 which is currently used

**Comment by alexrainman** [comment]
Merged manually.

**Pull request closed without merging**
