### PR TITLE
Proxy has been supported on iOS

### PR DESCRIPTION
**Pull request by MazZilaaaa**

### CODE REVIEW

**Comment by alexrainman** [comment]
Interesting. Will check how to implement this in Android and UWP before merging.

**Comment by MazZilaaaa** [comment]
Ok, before comment above, I didn't want do it and I felt bad myself. But after this comment, I will do.

**Comment by alexrainman** [comment]
Cannot fully merge your PR because it is only iOS but, I am using your implementation in iOS.

**Comment by alexrainman** [comment]
I was able to implement the proxy on all platforms. Now, how I can verify it is working? How you did it in iOS?

**Comment by alexrainman** [comment]
I tried setting Postman as my proxy but I cannot see the http calls being added to the History.

**Comment by MazZilaaaa** [comment]
In my project i use a local proxy [stunnel library](https://www.stunnel.org). It is started on my iOS device or simulator. But working with stunnel is some difficult. For simplicity you can use [jmeter](https://jmeter.apache.org). You should install it on your local machine and configure it as a proxy server. After, in your application, you should setup modernhttpclient proxy on your local proxy and launch application. When your application start send request, in jmetter you should see the requests and responses.

**Comment by MazZilaaaa** [comment]
I will try to use new version of library.

**Comment by alexrainman** [comment]
Latest version supports proxies in all platforms.

**Comment by MazZilaaaa** [comment]
I know, but I don't have a windows machine.

**Pull request closed without merging**
